#!/usr/bin/env bash
echo "php-cs-fixer pre-commit hook start"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

if [ -n "$CHANGED_FILES" ]; then
    composer style-fix $CHANGED_FILES;
    git add $CHANGED_FILES;
fi

echo "php-cs-fixer pre-commit hook finish"
echo "";
